name: Profile Checks

on:
  push:
    branches: [ master ]
    paths:
      - 'ci/check/profiles/**'
      - 'etc/**'
      - contrib/sort.py
      - src/firecfg/firecfg.config
  pull_request:
    branches: [ master ]
    paths:
      - 'ci/check/profiles/**'
      - 'etc/**'
      - contrib/sort.py
      - src/firecfg/firecfg.config

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  profile-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
    - name: sort.py
      run: ./ci/check/profiles/sort.py etc/inc/*.inc etc/{profile-a-l,profile-m-z}/*.profile
    - name: private-etc-always-required.sh
      run: ./ci/check/profiles/private-etc-always-required.sh etc/inc/*.inc etc/{profile-a-l,profile-m-z}/*.profile
    - name: sort-disable-programs.sh
      run: ./ci/check/profiles/sort-disable-programs.sh etc/inc/disable-programs.inc
    - name: sort-firecfg.config.sh
      run: ./ci/check/profiles/sort-firecfg.config.sh src/firecfg/firecfg.config
